---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voter
  name: voter-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voter-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voter-app
    spec:
      containers:
      - image: Nushan23/VoterAPI:main
        imagePullPolicy: Always
        name: voter-app
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  namespace: voter
  name: voter-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: voter-app
  type: LoadBalancer
status:
  loadBalancer: {}